services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flight-checker-app
    restart: always
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - VERBOSE_LOGGING=True
      # Streamlit forces lookups on standard web sockets
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"  # <-- HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./auth:/etc/nginx/auth:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/zenzic-site:/var/www/zenzic-site:ro
    depends_on:
      - app